{% set name = "marshmallow-sqlalchemy" %}
{% set version = "0.13.1" %}
{% set sha256 = "f3e1f27c83a013b114c26c8fad59980067030b0db9863b7ff52b31ce85620201" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - marshmallow >=2.0.0
    - sqlalchemy >=0.9.7

test:
  imports:
    - marshmallow_sqlalchemy

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy integration with marshmallow'

  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
