{% set name = "marshmallow-sqlalchemy" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marshmallow_sqlalchemy-{{ version }}.tar.gz
  sha256: 6410304bf98ec26ea35f3f9d3cee82e51fd093c434612add32a0bdcdb5668f7c

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python >=3.6
    - marshmallow >=3.18.0
    - sqlalchemy >=1.4.40,<3.0
    - typing-extensions  # [py<310]

test:
  source_files:
    - tests
  imports:
    - marshmallow_sqlalchemy
  requires:
    - pip
    - python
    - pytest
  commands:
    - pip check
    # skipping test due to not have pytest-lazy-fixtures
    - pytest -vv tests --ignore="tests/test_sqlalchemy_schema.py"

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy integration with marshmallow'

  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
    - igortg
