travis:
  secure:
    BINSTAR_TOKEN: Aqc6KstGelHX0Fs24rZVN+ymotJ+K7HUHdqE/yNVipdMtcXpUkoyBTnBZHASuNBBD3kdSr57MsnTjremAkFX5owkTdj0DQafExAgfP8PyjiNcLGatVJzjB/D86BCcmC8OSKxZvhtpPeAdcU1kogHmO5GPPhFIIoiYk9F73wAfImp1FH9r3R6vE+Ro8b0RrlqZTx7Ksfi25cF/ugt1hok69ut5BAsBj2u+9M9CUR8HTmT9XbZjzMwDk2eUsaZ8+Of9MsV59V6+QIdhxpJWpQ4EM9vg6M2cT47GrG+3zkILrZ7NL1y5npI7p5BEtGpI6KFYBe78MDnWZ8SjS2EhO7JZ+Llc3opvnG1xSYn8+sUGDmnU2HMIuhA9OllLSyIIWrD4O2QNXpEE+hmyY8RRQhJTLaRMWc80syk/PAAG1pG6do7xRsqOGWZqFzv9K7ZQK1/hSpLpToGg57i9Y7oyQ3kFtc4FRaHrXaVjBSbYBBuFmNam2HessB9lERA52nrs1XqDstwfLeQ6b69T6JT+30Xbe7EjQB5GvsX8c/xaA9BLYnoZy+HZDj+dkLmejH680uiDlxU3MM6XGIeZ9jw+0o9Ua3OsZZS7HHX8Uh8+3e0vJ+VXAOfj5D3D6bowDsAgUpE3sPqeGFItxFcKg/EjSr7STIQcQWPfl0bxtv+m6lyeLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
